### ISSUE TITLE
how to fix ?

### ISSUE THREAD

**Issue by Imaroubat** [glad-tidings/DragonzLandBot#4]
Unhandled exception. System.ArgumentNullException: Value cannot be null. (Parameter 'source')
   at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
   at System.Linq.Enumerable.Where[TSource](IEnumerable`1 source, Func`2 predicate)
   at DragonzLandBot.Program.DragonzLandThread(DragonzLandQuery Query) in C:\xxx\xxx\Desktop\xxx\DragonzLandBot\Program.cs:line 71
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()

**Comment by glad-tidings** [comment]
use new version
https://github.com/glad-tidings/DragonzLandBot-New
